# Generated by Django 4.2.28 on 2026-03-02 11:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('stock_level', models.PositiveIntegerField(default=0)),
                ('reorder_point', models.PositiveIntegerField(default=10)),
                ('max_stock', models.PositiveIntegerField(default=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('last_restocked', models.DateTimeField(blank=True, null=True)),
                ('is_ai_product', models.BooleanField(default=False)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('origin_country', models.CharField(blank=True, max_length=100)),
                ('sire_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('genetic_traits', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category')),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='inventory_p_categor_471092_idx'), models.Index(fields=['is_ai_product'], name='inventory_p_is_ai_p_7234d1_idx'), models.Index(fields=['stock_level'], name='inventory_p_stock_l_a63cdb_idx')],
            },
        ),
    ]
