# Generated by Django 4.2.28 on 2026-03-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Nicmah Agrovet', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=16, max_digits=5)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('mpesa_consumer_key', models.CharField(blank=True, max_length=255)),
                ('mpesa_consumer_secret', models.CharField(blank=True, max_length=255)),
                ('mpesa_shortcode', models.CharField(blank=True, max_length=20)),
                ('mpesa_passkey', models.CharField(blank=True, max_length=255)),
                ('mpesa_callback_url', models.CharField(blank=True, max_length=500)),
                ('receipt_footer', models.TextField(blank=True)),
                ('enable_etims', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
